# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container (This will make a folder named as app in the docker image)
WORKDIR /app

# Copy the current whole directory in this folder of app of docker image
COPY . /app

# install all the needed packages required for the docker image specified in the requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 avaiable to the world outside this container
EXPOSE 5000

# Define enviorment variable(Every time when we call FLASK_APP this will run app.py)
ENV FLASK_APP=app.py

# Run the flask app
CMD ["flask","run","--host=0.0.0.0"]